// fixtures/svelte/src/Button.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    interface Props {
        variant?: "primary" | "secondary";
        children: Snippet;
    }

    let { variant = "primary", children }: Props = $props();
</script>

<button
    style:padding="8px 16px"
    style:border-radius="4px"
    style:border="none"
    style:background-color={variant === "primary" ? "#007bff" : "#6c757d"}
    style:color="white"
    style:cursor="pointer"
>
    {@render children?.()}
</button>

// fixtures/solid/src/Button.tsx
import type { JSX } from "solid-js";

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: "primary" | "secondary";
}

export function Button(props: ButtonProps) {
    const variant = () => props.variant ?? "primary";

    return (
        <button
            {...props}
            style={{
                padding: "8px 16px",
                "border-radius": "4px",
                border: "none",
                "background-color": variant() === "primary" ? "#007bff" : "#6c757d",
                color: "white",
                cursor: "pointer",
                ...props.style,
            }}
        />
    );
}
